[application]

[web.app]

# HTML title tag content
title = "dioxus-e-commerce"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# [web.https] https://github.com/DioxusLabs/dioxus/pull/1182
# enabled = true
