[build]
  command = "cargo install dioxus-cli && dx bundle --platform web"
  publish = "dist"
  # functions = "functions"  # Only needed for SSR

[build.environment]
  RUST_VERSION = "stable" 

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200