[build]
  command = "dx bundle --platform web --release --target wasm32-unknown-unknown"
  publish = "dist"
  # functions = "functions"  # Only needed for SSR

[build.environment]
  RUST_VERSION = "stable" 
  CARGO_HOME = "/opt/buildhome/.cargo"
  RUSTUP_HOME = "/opt/buildhome/.rustup"

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200